"""empty message

Revision ID: e8c56611411a
Revises: 61578ea4ac70
Create Date: 2025-10-31 01:08:00.930878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c56611411a'
down_revision = '61578ea4ac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('zipcode',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('zipcode',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
